version: '3'
services:
  querkledb:
    image: postgres:latest
    environment:
      - POSTGRES_USER=quser
      - POSTGRES_PASSWORD=qpass
      - POSTGRES_DB=qdb
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"