version: '3'
services:
  querkle:
    image: querkle:latest
    command: bash -c "./wait-for-it/wait-for-it.sh -h querkledb -p 5432 -t 30 && npm run prepare-test-db && npm run test-cmd"
    links:
      - querkledb
    depends_on:
      - querkledb

  querkledb:
    image: postgres:latest
    environment:
      - POSTGRES_USER=quser
      - POSTGRES_PASSWORD=qpass
      - POSTGRES_DB=qdb
    ports:
      - "5432:5432"