version: '3'
services:
  querkle:
    image: querkle:latest
    command: bash -c "./wait-for-it/wait-for-it.sh -h db -p 1433 -t 30 && npm run prepare-test-db && npm run test-cmd"
    links:
      - db
    depends_on:
      - db
    environment:
      - SERVICE_DATABASE_NAME=querkle
      - SERVICE_DATABASE_SERVER=db
      - SERVICE_DATABASE_USER=SA
      - SERVICE_DATABASE_PASSWORD=Testpassword123
  db:
    image: "mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Testpassword123
    restart: always
    ports:
      - "1433:1433"